### ISSUE TITLE
这个模型是一阶段还是两阶段的跟踪。怎么感觉像是两阶段的跟踪模型

### ISSUE THREAD

**Issue by David1-git** [RainBowLuoCS/DiffusionTrack#6]
如题，还望大佬指教

**Comment by RainBowLuoCS** [comment]
The key difference between the one-stage and two-stage methods is whether the tracking results and the detection results are output by the model at the same time, and our method is an end-to-end one-stage method because the tracking and detection results are obtained by the model end-to-end. If it is a two-stage method like ByteTrack, the detection results are obtained first through an advanced detector, and then the association is done using Kalman Filter.

**Comment by David1-git** [comment]
但是不是很理解为什么在训练的时候要分别训练一次检测和跟踪：
python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_det_mot20.py -d 8 -b 16 -o -c pretrained/bytetrack_x_mot20.pth.tar
python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_track_mot20.py -d 8 -b 16 -o -c pretrained/diffusiontrack_mot20_det.pth.tar

**Comment by RainBowLuoCS** [comment]
直觉上先在简单的检测任务上训练保证跟踪训练收敛，你也可以直接训练跟踪，因为跟踪包含了检测的子范式，我还没有试过



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [RainBowLuoCS/DiffusionTrack] 这个模型是一阶段还是两阶段的跟踪。怎么感觉像是两阶段的跟踪模型 (Issue #6)





 
但是不是很理解为什么在训练的时候要分别训练一次检测和跟踪：
 python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_det_mot20.py -d 8 -b 16 -o -c pretrained/bytetrack_x_mot20.pth.tar
 python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_track_mot20.py -d 8 -b 16 -o -c pretrained/diffusiontrack_mot20_det.pth.tar

**Comment by David1-git** [comment]
> 直觉上先在简单的检测任务上训练保证跟踪训练收敛，你也可以直接训练跟踪，因为跟踪包含了检测的子范式，我还没有试过
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月28日(星期二) 晚上7:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [RainBowLuoCS/DiffusionTrack] 这个模型是一阶段还是两阶段的跟踪。怎么感觉像是两阶段的跟踪模型 (Issue #6) 但是不是很理解为什么在训练的时候要分别训练一次检测和跟踪： python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_det_mot20.py -d 8 -b 16 -o -c pretrained/bytetrack_x_mot20.pth.tar python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_track_mot20.py -d 8 -b 16 -o -c pretrained/diffusiontrack_mot20_det.pth.tar — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

跟踪需要的预训练模型diffusiontrack_mot20_det.pth.tar不是前面检测训练的模型么。还是说可以把diffusiontrack_mot20_det.pth.tar换成bytetrack_x_mot20.pth.tar然后直接训练跟踪模型。像这样python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_track_mot20.py -d 8 -b 16 -o -c pretrained/bytetrack_x_mot20.pth.tar

**Comment by RainBowLuoCS** [comment]
确实可以，只需要把backbone对应的那块权重放进去就行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月29日(星期三) 晚上6:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [RainBowLuoCS/DiffusionTrack] 这个模型是一阶段还是两阶段的跟踪。怎么感觉像是两阶段的跟踪模型 (Issue #6)





  
直觉上先在简单的检测任务上训练保证跟踪训练收敛，你也可以直接训练跟踪，因为跟踪包含了检测的子范式，我还没有试过
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月28日(星期二) 晚上7:48 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [RainBowLuoCS/DiffusionTrack] 这个模型是一阶段还是两阶段的跟踪。怎么感觉像是两阶段的跟踪模型 (Issue #6) 但是不是很理解为什么在训练的时候要分别训练一次检测和跟踪： python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_det_mot20.py -d 8 -b 16 -o -c pretrained/bytetrack_x_mot20.pth.tar python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_track_mot20.py -d 8 -b 16 -o -c pretrained/diffusiontrack_mot20_det.pth.tar — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
跟踪需要的预训练模型diffusiontrack_mot20_det.pth.tar不是前面检测训练的模型么。还是说可以把diffusiontrack_mot20_det.pth.tar换成bytetrack_x_mot20.pth.tar然后直接训练跟踪模型。像这样python3 tools/train.py -f exps/example/mot/yolox_x_diffusion_track_mot20.py -d 8 -b 16 -o -c pretrained/bytetrack_x_mot20.pth.tar

**Comment by David1-git** [comment]
原来的模型类别数是1，我现在换了另一个数据集，把类别数改成了12，然后在模型评估的时候报错说有个维度要求是500，但是输入的是6000维，猜想应该是和类别数有关12＊500=6000。但是debug了一下代码没有找到在哪里修改，大佬可以帮忙看一下应该在哪里修改嘛，感谢感谢！

**Comment by David1-git** [comment]
DiffusionTrack/diffusion/models/diffusion_head.py", line 351, in new_ddim_sample return torch.cat([box_pred.view(2batch,-1,4),box_cls.view(2*batch,-1,1)],dim=-1),conf_score.view(batch,-1,1),total_time │     │    │        │      │           │       │      │                    │          │    │           └ 0.23464202880859375 │     │    │        │      │           │       │      │                    │          │    └ 2 │     │    │        │      │           │       │      │                    │          └ <method 'view' of 'torch._C._TensorBase' objects> │     │    │        │      │           │       │      │                    └ tensor([[[2.5723e-05], │     │    │        │      │           │       │      │                               [3.5651e-05], │     │    │        │      │           │       │      │                               [2.7678e-05], │     │    │        │      │           │       │      │                               [3.1642e-05], │     │    │        │      │           │       │      │                               [3.0410e-05], │     │    │        │      │           │       │      │                               [... │     │    │        │      │           │       │      └ 2 │     │    │        │      │           │       └ <method 'view' of 'torch._C._TensorBase' objects> │     │    │        │      │           └ tensor([[[  3.1921, -10.8435, -11.5519,  ..., -10.2219,  -9.3962, -10.0006], │     │    │        │      │                      [  4.3959, -11.2550, -12.2002,  ..., -1... │     │    │        │      └ 2 │     │    │        └ <method 'view' of 'torch._C._TensorBase' objects> │     │    └ tensor([[[ 626.1824,  238.7088,  626.1824,  238.7088], │     │               [ 616.3925,   65.4778,  616.3925,   65.4778], │     │               [1585.... │     └ <built-in method cat of type object at 0x7faf4af9f1e0> └ <module 'torch' from '/home/valca509/anaconda3/envs/diffusion/lib/python3.8/site-packages/torch/init.py'>RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 500 but got size 6000 for tensor number 1 in the list.
这个是报错的信息

**Comment by David1-git** [comment]
DiffusionTrack/diffusion/models/diffusion_head.py", line 351, in new_ddim_sample return torch.cat([box_pred.view(2batch,-1,4),box_cls.view(2*batch,-1,1)],dim=-1),conf_score.view(batch,-1,1),total_time │     │    │        │      │           │       │      │                    │          │    │           └ 0.23464202880859375 │     │    │        │      │           │       │      │                    │          │    └ 2 │     │    │        │      │           │       │      │                    │          └ <method 'view' of 'torch._C._TensorBase' objects> │     │    │        │      │           │       │      │                    └ tensor([[[2.5723e-05], │     │    │        │      │           │       │      │                               [3.5651e-05], │     │    │        │      │           │       │      │                               [2.7678e-05], │     │    │        │      │           │       │      │                               [3.1642e-05], │     │    │        │      │           │       │      │                               [3.0410e-05], │     │    │        │      │           │       │      │                               [... │     │    │        │      │           │       │      └ 2 │     │    │        │      │           │       └ <method 'view' of 'torch._C._TensorBase' objects> │     │    │        │      │           └ tensor([[[  3.1921, -10.8435, -11.5519,  ..., -10.2219,  -9.3962, -10.0006], │     │    │        │      │                      [  4.3959, -11.2550, -12.2002,  ..., -1... │     │    │        │      └ 2 │     │    │        └ <method 'view' of 'torch._C._TensorBase' objects> │     │    └ tensor([[[ 626.1824,  238.7088,  626.1824,  238.7088], │     │               [ 616.3925,   65.4778,  616.3925,   65.4778], │     │               [1585.... │     └ <built-in method cat of type object at 0x7faf4af9f1e0> └ <module 'torch' from '/home/valca509/anaconda3/envs/diffusion/lib/python3.8/site-packages/torch/init.py'>RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 500 but got size 6000 for tensor number 1 in the list.
这个是报错信息
